#mkdir my-repo && cd my-repo   # or cd into an existing empty folder you want to use
#git init
#git remote add origin https://github.com/onartey/test-repo/edit/main/.github/workflows/ci-trigger.yaml
#git sparse-checkout init --cone
#git sparse-checkout set src
#git pull origin main#

name: Microservices Trigger CI

on:
  workflow_dispatch:
  push: 
    branches: main
  pull_request:
    branches: main
    
permissions:
  contents: read
  packages: write

jobs:
  detect-changes: 
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.changes }}
    steps: 
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend: 'src/frontend/**'
            checkoutservice: 'src/checkoutservice/**'
            cartservice: 'src/cartservice/**'
            productcatalogservice: 'src/productcatalogservice/**'
            recommendationservice: 'src/recommendationservice/**'
            adservice: 'src/adservice/**'
            shippingservice: 'src/shippingservice/**'
            currencyservice: 'src/currencyservice/**'
            paymentservice: 'src/paymentservice/**'
            emailservice: 'src/emailservice/**'
      
  build:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.services != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.services || '[]') }}
    uses: ./.github/workflows/microservice-ci.yaml
    with:
      service: ${{ matrix.service }}
