#Here, this is where the actual file is going to be called by the trigger.yaml file using the workflow_call keyword with inputs from that worfklow.

name: Microservice CI

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Echo service name
        run: |
          echo "Service: ${{ inputs.service }}"

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.service }} ./src/${{ inputs.service }}

        
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
